Update CONTRIBUTING.md with more details for package setup
aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions pull request #36
Opened 2022-08-11 20:16 UTC by jormello

*Description of changes:*
Provides additional information in `CONTRIBUTING.md` with how to set up the resource provider package in your IDE.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-15 17:59 UTC, evscott requested changes

2022-08-15 17:59 UTC, evscott commented on CONTRIBUTING.md
> +7. Pay attention to any automated CI failures reported in the pull request, and stay involved in the conversation.
The ordering here is off now.

2022-08-15 18:02 UTC, evscott commented
Looks good overall. Just one comment to address.

2022-08-16 13:17 UTC, jormello commented on CONTRIBUTING.md
> +7. Pay attention to any automated CI failures reported in the pull request, and stay involved in the conversation.
Good find, updated!

2022-10-13 16:43 UTC, abdelnn approved these changes

2022-10-13 17:30 UTC, hongkuntian approved these changes

2022-10-13 18:34 UTC, yonakim57 approved these changes

2022-10-31 17:00 UTC, evscott approved these changes

2022-11-01 14:20 UTC, merged