Add stabilization to Activity Delete handler
aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions pull request #51
Opened 2024-01-31 01:21 UTC by hongkuntian

*Issue #, if available:* N/A

*Description of changes:*

Add stabilization to `AWS::StepFunctions::Activity` resource's Delete handler

Motivation:

`DescribeActivity` operation is eventually consistent. The results are best effort and may not reflect very recent updates and changes. This results in the Read handler not always retrieving the correct state after the deletion of an activity. (e.g. Invoke Delete handler, and the immediately invoking Read handler may return the activity details despite the activity having been deleted)

This change follows CloudFormation's best practices in how to develop resource handlers:

> DO NOT delegate the response of the model, check existence, or stabilization in CREATE, UPDATE and DELETE handler to the READ handler

This change adds the following logic to stabilize the deletion:

* After calling `DeleteActivity`, we now call `DescribeActivity` consecutively for `STABILIZATION_CALL_COUNT = 10` number of times.
  1. If all `DescribeActivity` calls fail, then the Delete handler returns `SUCCESS`
  2. If any `DescribeActivity` successfully returns the deleted activity, we set `callBackDelaySeconds`  based on a rudimentary `ExponentialBackoffDelayWithJitter` helper method, and return `IN_PROGRESS`. This will allow the Delete handler to retry the 10 consecutive `DescribeActivity` calls after `callBackDelaySeconds` has passed.
  2. We allow 3 retry attempts, and if all attempts fail, we return `SUCCESS` to preserve backwards compatibility.

The above logic is made possible by setting variables in the CallbackContext, so each invocation of the Delete handler has context on whether we have already deleted activity/which retry attempt we are on.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-20 18:19 UTC, abdelnn requested changes
2 small comments, otherwise looks good!

2024-02-20 18:19 UTC, abdelnn commented on activity/src/main/java/com/amazonaws/stepfunctions/cloudformation/activity/CallbackContext.java
> +@lombok.EqualsAndHashCode(callSuper = true)
Why are we adding these, they should already be added as part of `@Data`

2024-02-20 18:19 UTC, abdelnn commented on activity/src/main/java/com/amazonaws/stepfunctions/cloudformation/activity/DeleteHandler.java
> +                    return stabilizeDeleteActivity(proxy, model, callbackContext.getRetryCount(), logger);
Might be unnecessary to call `callbackContext.getRetryCount` when we already set it a line above

```suggestion
                    return stabilizeDeleteActivity(proxy, model, currentRetryCount + 1, logger);
```

2024-02-20 19:37 UTC, abdelnn approved these changes

2024-02-20 21:28 UTC, jormello requested changes

2024-02-20 21:28 UTC, jormello commented on activity/src/main/java/com/amazonaws/stepfunctions/cloudformation/activity/DeleteHandler.java
> +            }
If we do 3 retries, waiting up to a maximum of 30s on the final attempt, we will exceed the 60s timeout within which we have to return a progress event. 

Could we implement this such that the CallbackContext maintains a count of the number of successive DescribeActivity attempts that return with the activity not existing? If we get a DescribeActivity call that returns as a `200`, then we reset the count to `0`.

2024-02-23 19:33 UTC, jormello approved these changes

2024-02-23 19:45 UTC, merged